# Generated by Django 2.1 on 2018-11-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylist',
            name='published_time',
            field=models.TimeField(null=True),
        ),
    ]
