# Generated by Django 2.1 on 2018-11-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_deploylist_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploylist',
            name='build_status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('running', 'running'), ('FAILURE', 'FAILURE')], max_length=128),
        ),
        migrations.AlterField(
            model_name='deploylist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deploylist',
            name='last_build_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='deploylist',
            name='published_time',
            field=models.DateTimeField(null=True),
        ),
    ]
