# Generated by Django 2.1 on 2018-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20181114_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylist',
            name='last_success_build_num',
            field=models.IntegerField(null=True),
        ),
    ]
