# Generated by Django 2.1 on 2018-11-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_deploylist_last_success_build_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylist',
            name='last_build_num',
            field=models.IntegerField(null=True),
        ),
    ]
