# Generated by Django 2.1 on 2018-11-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_deploylist_last_build_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploylist',
            name='deploy_file_path',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='deploylist',
            name='build_status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('RUNNING', 'RUNNING'), ('FAILURE', 'FAILURE')], max_length=128),
        ),
    ]
