# Generated by Django 2.1 on 2018-11-19 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0010_deploylist_build_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployversion',
            name='app_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deploy.DeployList', verbose_name='App Name'),
        ),
    ]
